<div class="footer_top">
	<div class="footer_top_wrap">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_tags')->toHtml() ?>
        <div class="clr"></div>    	
    </div>
</div>

<div id="org-footer" class="default">
<div id="org-footer-inner">
	<div id="logo-glow"></div>
	<div class="close">close</div>

	<div class="logos">
		<a id="org-logo-fa" class="logo" data-id="logo01" href="http://www.foundanimals.org" title="Found Animals Pet Care, Spay &amp; Neuter, Adopt a Dog &amp; Cat, Pets Jobs LA"><div>Found Animals</div></a>
		<a id="org-logo-registry" class="logo" data-id="logo02" href="https://microchipregistry.foundanimals.org/"><div>Found Animals Registry</div></a>
		<a id="org-logo-mpg" class="logo" data-id="logo03" href="http://michelsonprizeandgrants.org/" title="Michelson Prize &amp; Grants"><div>Michelson Prize &amp; Grants</div></a>
		<a id="org-logo-adopt-and-shop" class="logo" data-id="logo04" href="https://www.adoptandshop.org/"><div>Adopt &amp; Shop</div></a>
	</div>

	<div class="info">
		<div class="text logo01" data-id="logo01">
			Found Animals primary mission is the happiness and safety of animals. From microchips and registration, to responsible adoption initiatives and low-cost spay and neuter surgeries, we are committed to delivering practical solutions that will ensure the health and safety of dogs and cats nationwide. At Found Animals, we’re on the animal’s side.
			<a href="http://www.foundanimals.org" target="_blank">Visit Site &raquo;</a>
		</div>
		<div class="text logo02" data-id="logo02">
			The Found Animals Registry was built for one reason: to reunite all lost pets with their families. We are dedicated to providing the simplest, most straightforward solution to make our mission a reality. By offering free registration for all microchip brands, we make it easy for pet owners to register and update their pets’ microchips.
			<a href="https://microchipregistry.foundanimals.org/" target="_blank">Visit Site &raquo;</a>
		</div>
		<div class="text logo03" data-id="logo03">
			In 2008, Found Animals launched the $75 million Michelson Prize & Grants in Reproductive Biology in pursuit of a single-dose, nonsurgical sterilant for cats and dogs. We envision a world in which this product is widely available to animal care professionals as a means to eliminate shelter euthanasia.
			<a href="http://michelsonprizeandgrants.org/" target="_blank">Visit Site &raquo;</a>
		</div>
		<div class="text logo04" data-id="logo04">
			Adopt & Shop is committed to creating opportunities for every animal to find a home and the resources to live a long, happy life. As part of Found Animals, we put our money where our hearts are, reinvesting proceeds to improve the well-being of animals everywhere. As a 501(c)(3) nonprofit organization we are for pets, not for profit.
			<a href="https://www.adoptandshop.org/" target="_blank">Visit Site &raquo;</a>
		</div>
	</div>
</div>
</div>

<div class="footer_bottom">
	<div class="footer_wrap">
    	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
    	<div class="clr"></div>
        <div class="caption"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_tagline')->toHtml();?></div>
    </div>
</div>
