<div class="store-locator">
	<div class="map"><img src="<?php echo $this->getSkinUrl('images/locator.png') ?>" alt="banner" /></div>
    <div class="location">
    	<h1>Location</h1>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
        </p>
    </div>
    
    <div class="shop-location">
    	<ul>
        	<li>
            	<div class="left-cell">
                	<div class="img-box"><img src="<?php echo $this->getSkinUrl('images/location.jpg') ?>" alt="banner" /></div>
                    <div class="btn"><button class="button_2"><span><span>Volunteer</span></span></button></div>
                    <div class="btn"><button class="button_2"><span><span>Appointment</span></span></button></div>
                    <div class="btn"><button class="button"><span><span>Adoptable Pets</span></span></button></div>
                </div>
                <div class="right-cell">
                	<h3>Lakewood Adop &amp; Shop</h3>
                    <p>353 Lakewood Center Mall Lakewood, CA,90712 </p>
                    <h4>Get Direction</h4>
                    <p>MON. -SAT.<br /> 10:10 AM-9:00 PM<br /> SUN.<br />10:10 AM-9:00 PM</p>
                    <h5>562-531-2871</h5>
                </div>
            </li>
            <li>
            	<div class="left-cell">
                	<div class="img-box"><img src="<?php echo $this->getSkinUrl('images/location.jpg') ?>" alt="banner" /></div>
                    <div class="btn"><button class="button_2"><span><span>Volunteer</span></span></button></div>
                    <div class="btn"><button class="button_2"><span><span>Appointment</span></span></button></div>
                    <div class="btn"><button class="button"><span><span>Adoptable Pets</span></span></button></div>
                </div>
                <div class="right-cell">
                	<h3>Lakewood Adop &amp; Shop</h3>
                    <p>353 Lakewood Center Mall Lakewood, CA,90712 </p>
                    <h4>Get Direction</h4>
                    <p>MON. -SAT.<br /> 10:10 AM-9:00 PM<br /> SUN.<br />10:10 AM-9:00 PM</p>
                    <h5>562-531-2871</h5>
                </div>
            </li>
            <li>
            	<div class="left-cell">
                	<div class="img-box"><img src="<?php echo $this->getSkinUrl('images/location.jpg') ?>" alt="banner" /></div>
                    <div class="btn"><button class="button_2"><span><span>Volunteer</span></span></button></div>
                    <div class="btn"><button class="button_2"><span><span>Appointment</span></span></button></div>
                    <div class="btn"><button class="button"><span><span>Adoptable Pets</span></span></button></div>
                </div>
                <div class="right-cell">
                	<h3>Lakewood Adop &amp; Shop</h3>
                    <p>353 Lakewood Center Mall Lakewood, CA,90712 </p>
                    <h4>Get Direction</h4>
                    <p>MON. -SAT.<br /> 10:10 AM-9:00 PM<br /> SUN.<br />10:10 AM-9:00 PM</p>
                    <h5>562-531-2871</h5>
                </div>
            </li>
        </ul>
        <div class="clr"></div>
    </div>
</div>
