<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<style>
.gmnoprint img { max-width: none; }
      #directions-panel {
        height: 500px;
        float: right;
      /*  width: 390px;*/
        overflow: auto;
      }

      #map-canvas {
        /*margin-right: 400px;*/
		height:500px;
		/*width:900px;*/
      }

	#control {
        background: #fff;
        padding: 5px;
        font-size: 14px;
        font-family: Arial;
        border: 1px solid #ccc;
        box-shadow: 0 2px 2px rgba(33, 33, 33, 0.4);
        display: none;
		margin:5px;
      }
      @media print {
        #map-canvas {
          height: 500px;
          margin: 0;
        }

        #directions-panel {
          float: none;
          width: auto;
        }
      }
    </style>
<script language="javascript">
jQuery(document).ready(function(){
				jQuery(".inline").colorbox({
					inline:true, 
					width:"90%",
					height: "800px",
					/*onOpen:function(){ initialize(document.getElementById('start_lat').value,document.getElementById('start_lng').value) },
					onLoad:function(){ alert('onLoad: colorbox has started to load the targeted content'); },*/
					onComplete:function(){ var store_id  = document.getElementById('store_id').value; document.getElementById('store_hour').innerHTML = document.getElementById('hour'+store_id).innerHTML; initialize(document.getElementById('start_lat').value,document.getElementById('start_lng').value); },
					/*onCleanup:function(){ alert('onCleanup: colorbox has begun the close process'); },*/
					onClosed:function(){ document.getElementById('address').value = '';document.getElementById('store_address').value = ''; document.getElementById('store_hour').value = ''; document.getElementById('store_hour').innerHTML = ''; document.getElementById('store_address').innerHTML = ''; jQuery('#directions-panel').css('width', '0');}
				});
				
			});
		</script>
 
		

<input type="hidden" name="start_lat" id="start_lat" />
<input type="hidden" name="start_lng" id="start_lng" />
<input type="hidden" name="store_id" id="store_id" />

<div class="static_banner stor-location">
	<img src="<?php echo $this->getSkinUrl('images/store_locator.jpg') ?>" alt="banner" />
    <div class="banner_block">
    <!--<h2>Adopt &amp; shop <br />store locator</h2>-->
    <p>Found Animals Adopt &amp; Shop unites pet adoption, retail, and philanthropy to ensure all pets have the opportunity to live in the home of a lifetime. Our physical locations unite adoptable dogs and cats from local shelters with loving homes.
</p>
    <!--<div class="btn"><a href="#">Register Today</a></div>-->
    </div>
</div>
<div class="store-locator">
    <!--<div class="location">
    	<h1>Location</h1>
        <div class="location_descrip">
        <?php /*?><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('locatioin_descripr')->toHtml() ?><?php */?>
        </div>
    </div>-->
    
    <div class="shop-location">
    	<ul>
        	<!--<li>
            	<div class="left-cell">
                	<div class="img-box"><img src="<?php echo $this->getSkinUrl('images/location.jpg') ?>" alt="banner" /></div>
                    <div class="btn"><button class="button_2"><span><span>Volunteer</span></span></button></div>
                    <div class="btn"><button class="button_2"><span><span>Appointment</span></span></button></div>
                    <div class="btn"><button class="button"><span><span>Adoptable Pets</span></span></button></div>
                </div>
                <div class="right-cell">
                	<h3>Lakewood Adop &amp; Shop</h3>
                    <p>353 Lakewood Center Mall Lakewood, CA,90712 </p>
                    <h4>Get Direction</h4>
                    <p>MON. -SAT.<br /> 10:10 AM-9:00 PM<br /> SUN.<br />10:10 AM-9:00 PM</p>
                    <h5>562-531-2871</h5>
                </div>
            </li>-->
			    <?php foreach($this->getStores() as $store) :?>

            <li>
            	<div class="cell-01">
                	<div class="img-box"><a href="<?php if($store->getStoreUrl() != ''){ echo $store->getStoreUrl();}else{ echo "javascript:;"; } ?>"><img src="<?php echo $store->getImage(); ?>" alt="banner" width="150" height="150"/></a></div>
                </div>
                <div class="cell-02">
                	<h3><a href="<?php if($store->getStoreUrl() != ''){ echo $store->getStoreUrl();}else{ echo "javascript:;"; } ?>"><?php echo $store->getName()?></a></h3>
                    <p><?php echo $store->getAddress()?></p>
					<p><?php echo $store->getCustomContent()?></p>
                    <h4><a class='inline' href="#inline_content" onclick="document.getElementById('start_lat').value = '<?php echo $store->getLat()?>'; document.getElementById('start_lng').value = '<?php echo $store->getLong()?>'; document.getElementById('store_address').innerHTML = '<?php echo $store->getName()?> <br /> <?php echo nl2br($store->getAddress())?>';  document.getElementById('store_id').value = '<?php echo $store->getEntityId()?>';">Get Directions</a></h4>
                    
                 </div>
                 <div class="cell-03">   
                    <p id="hour<?php echo $store->getEntityId()?>"><?php echo nl2br($store->getDescription());?></p>
                    <h5><?php echo $this->__($store->getPhone()); ?></h5>
                </div>
                <div class="cell-04">
                	<div class="btn"><button class="button" onclick="window.open('<?php echo $store->getAdoptablePetsUrl(); ?>', '_blank')"><span><span>View Adoptable Pets</span></span></button></div>
                    <div class="btn"><button class="button_2" /*onclick="window.open('<?php echo $store->getAppointmentUrl(); ?>', '_blank')"*/><span><span>Book an Appointment <label>Comming Soon</label></span></span></button></div>
                	<div class="btn"><button class="button_4" onclick="window.open('<?php echo $store->getVolunteerUrl(); ?>', '_blank')"><span><span>Volunteer</span></span></button></div>
                   
                </div>
                <div class="clr"></div>
            </li>
					<?php endforeach;?>

            <!--<li>
            	<div class="left-cell">
                	<div class="img-box"><img src="<?php echo $this->getSkinUrl('images/location.jpg') ?>" alt="banner" /></div>
                    <div class="btn"><button class="button_2"><span><span>Volunteer</span></span></button></div>
                    <div class="btn"><button class="button_2"><span><span>Appointment</span></span></button></div>
                    <div class="btn"><button class="button"><span><span>Adoptable Pets</span></span></button></div>
                </div>
                <div class="right-cell">
                	<h3>Lakewood Adop &amp; Shop</h3>
                    <p>353 Lakewood Center Mall Lakewood, CA,90712 </p>
                    <h4>Get Direction</h4>
                    <p>MON. -SAT.<br /> 10:10 AM-9:00 PM<br /> SUN.<br />10:10 AM-9:00 PM</p>
                    <h5>562-531-2871</h5>
                </div>
            </li>-->
        </ul>
        <div class="clr"></div>
    </div>
</div>
		<?php /*?><table id="store-table" class="store-table">
			<tbody>

				<tr>
					<td rowspan="8" class="store-image">
						<a class='inline' href="#inline_content"><img src="<?php echo $store->getImage(); ?>" alt="<?php echo $store->getName()?>" width="150"></a>
					</td>
				</tr>
				<tr>
					<td>
						<h3 class='store-name' id="store<?php echo $store->getId(); ?>"><a class='inline' href="#inline_content" onclick="document.getElementById('start_lat').value = '<?php echo $store->getLat()?>'; document.getElementById('start_lng').value = '<?php echo $store->getLong()?>';"><?php echo $store->getName()?></a></h3>
					</td>
				</tr>
				<tr>
					<td class="col-address">
						<?php echo $store->getAddress()?>
					</td>
				</tr>
				<tr>
					<td class="col-address">
						<?php echo $store->getZipcode()." ".$store->getCity()?>
					</td>
				</tr>
				<tr>
					<td class="col-address">
						<?php echo $store->getCountryId(); ?>
					</td>
				</tr>
				<tr>
					<td>
						<?php if(!is_null($store->getStoreUrl()) && $store->getStoreUrl() != ''):?>
							<?php echo $this->__('Website : %s', "<a href='".$store->getStoreUrl()."' target='_blank'>");?><?php echo $this->__('%s', $store->getStoreUrl());?></a>
						<?php endif; ?>
					</td>
				</tr>
				<tr>
					<td>
						<?php if(!is_null($store->getPhone())&& $store->getPhone()!= ''):?>
							<?php echo $this->__('Phone : %s', $store->getPhone()); ?>
						<?php endif; ?>
					</td>
				</tr>
				<tr>
					<td>
					 <?php if(!is_null($store->getFax()) && $store->getFax() != ''):?>
						   <?php echo $this->__('Fax : %s', $store->getFax());?>
					<?php endif; ?>
					</td>
				</tr>
			</tbody>
		</table><?php */?>


<script language="javascript">
var directionsDisplay;
var directionsService = new google.maps.DirectionsService();
var map;
var geocoder;
function initialize(start_lat,start_lng) {
    geocoder = new google.maps.Geocoder();

  directionsDisplay = new google.maps.DirectionsRenderer();
  var mapOptions = {
    zoom: 7,
	zoomControl: true,
	zoomControlOptions: {
             position: google.maps.ControlPosition.TOP_LEFT
        },
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    center: new google.maps.LatLng(start_lat, start_lng)
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
  directionsDisplay.setMap(map);
    var marker = new google.maps.Marker({
                position: new google.maps.LatLng(start_lat, start_lng),
                map: map,
                draggable: true
            });
           // map.setCenter(location); 
	  /*directionsDisplay.setPanel(document.getElementById('directions-panel'));*/

	 var control = document.getElementById('control');
	  control.style.display = 'block';
	 /* map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);*/
		   

}

function calcRoute(start,end) {
 // var start = document.getElementById('start').value;
  //var end = document.getElementById('end').value;
  directionsDisplay = new google.maps.DirectionsRenderer();
  var mapOptions = {
    zoom: 7,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    center: new google.maps.LatLng(41.850033, -87.6500523)
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
  directionsDisplay.setMap(map);
  
  var request = {
    origin: start,
    destination: end,
    travelMode: google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}
function codeAddress() {
  var address = document.getElementById('address').value;
  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      //map.setCenter(results[0].geometry.location);
     /* var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });*/
	  var endLocation  = new google.maps.LatLng(document.getElementById('start_lat').value, document.getElementById('start_lng').value);
		var request = {
			origin: results[0].geometry.location,
			destination: endLocation,
			travelMode: google.maps.TravelMode.DRIVING
		};
		directionsService.route(request, function(response, status) {
			if (status == google.maps.DirectionsStatus.OK) {
			    jQuery('#directions-panel').css({'width':'390','margin-left':'10px'});
				directionsDisplay = new google.maps.DirectionsRenderer();
  var mapOptions = {
    zoom: 7,
	zoomControl: true,
	zoomControlOptions: {
             position: google.maps.ControlPosition.TOP_LEFT
        },
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    center: new google.maps.LatLng(start_lat, start_lng)
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
  directionsDisplay.setMap(map);
    var marker = new google.maps.Marker({
                position: new google.maps.LatLng(start_lat, start_lng),
                map: map,
                draggable: true
            });
			directionsDisplay.setPanel(document.getElementById('directions-panel'));

	 var control = document.getElementById('control');
	  control.style.display = 'block';
				directionsDisplay.setDirections(response);

			}
		});
    } else {
      	alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
//google.maps.event.addDomListener(window, 'load', initialize);

    </script>

<div style='display:none'>
<div id='inline_content'>
<div id="search_map">
     <label for="address"><?php echo $this->__('Starting Location :');?></label>
     <input type="text" name="address" id="address" class="input-text"/> <a href="javascript:void(0);" onclick="codeAddress()">Get Directions</a>

 </div>
 <div class="store-address"><h5>Store Address:</h5><div id="store_address"></div></div>
 <div class="hour-track"><h5>Hour:</h5><div id="store_hour"></div></div>
 <div class="clr"></div>
<div id="control">
<div id="directions-panel"></div>
<div id="map-canvas"></div>
</div>
</div>
</div>
