<link href="<?php echo $this->getSkinUrl();?>css/jquery-ui-datepick.css" rel="stylesheet">
<script src="<?php echo $this->getSkinUrl();?>js/jquery-ui-datepick.js"></script>
<script>
  jQuery(function() {
    jQuery( "#guest_petbirthday" ).datepicker({
      changeMonth: true,
      changeYear: true,
	  dateFormat: 'mm/dd/y'
    });
  });
  </script>
<div class="subscription">
	<div class="subs_banner"><img src="<?php echo $this->getSkinUrl('images/subscription_new_banner.jpg') ?>" alt="banner" /></div>
	<div class="subs_form">
    	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-custom">

    <div class="field"><label><em>*</em>First Name:</label> <input type="text" name="guest_firstname" id="guest_firstname" class="input-text required-entry"/></div> 
    <div class="field"><label><em>*</em>Last Name:</label> <input type="text" name="guest_lastname" id="guest_lastname" class="input-text required-entry" /></div>
  
  <div class="field"><label><em>*</em>Email Address:</label> <input type="text" name="email" id="email" class="input-text required-entry validate-email" /></div>
    <div class="field"><label><em>*</em>Zip Code:</label> <input type="text" name="guest_zipcode" id="guest_zipcode" class="input-text required-entry" /></div>
  
  <div class="field"><label><em>*</em>Street 1:</label> <input type="text" name="guest_street1" id="guest_street1" class="input-text required-entry" /></div>
    <div class="field"><label>Street 2:</label> <input type="text" name="guest_street2" id="guest_street2" class="input-text" /></div>
  
  <div class="field"><label><em>*</em>City:</label> <input type="text" name="guest_city" id="guest_city" class="input-text required-entry" /></div>
    <div class="field"><label><em>*</em>State:</label>
    <div class="select-box">
    <select name="guest_state" id="guest_state" class="validate-select"/>
		<?php
			$regionArray = Mage::getModel('directory/country')->load('US')->getRegions()->toOptionArray();
			foreach($regionArray as $index=>$data):
			?>
			<option value="<?php echo ($data['value'] == 0)? '': $data['label'];?>"><?php echo $data['label'];?></option>
			<?php
			endforeach;
			//print_r($regionArray);
		?>
	</select>
    </div>
	</div>
    
    <div class="field"><label>Pet Name:</label> <input type="text" name="guest_petname" id="guest_petname" class="input-text" /></div>
    <div class="field"><label>Pet Birthday:</label> <input type="text" name="guest_petbirthday" id="guest_petbirthday" class="input-text validate-date"/><?php /*?><img title="Select date" id="cal_date_trig" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>"  class="v-middle calendar" style="display:block;"/><?php */?></div>
  
   <div class="btn"><button type="submit" class="button" title="<?php echo $this->__('Subscribe') ?>"><span><span><?php echo $this->__('Submit') ?></span></span></button>
   <p class="required">* Required Fields</p>
   </div>
</form>
	<div class="clr"></div>
	
    </div>
    
    
    <div class="clr"></div>
    <div class="descrip"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('subscrip_descrip')->toHtml() ?></div>
</div>

<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-custom');
//]]>
</script>
<script type="text/javascript">// <![CDATA[
/*Calendar.setup({
    inputField : 'guest_petbirthday',
    ifFormat : '%m/%e/%y',
    button : 'cal_date_trig',
    align : 'Bl',
    singleClick : true
});*/

// ]]></script>
